name: NodeJS with Webpack, and push to github pages

on:
  push:
    branches: [ main,master ]
  pull_request:
    branches: [ main,master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build webpack to dist folder
      run: |
        yarn
        yarn run build
        cp ./index.html ./dist/index.html
    - name: Deploy to GH Page
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: dist 
